name: Only build
on:
  push:
    branches: ['develop']


jobs:
  build-image:
    name: Build Docker images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: cardinalby/export-env-action@v2
        with:
          envFile: '.env'  

      # Versioned main image
      - name: Build and push Docker - main release
        if: always()
        uses: docker/build-push-action@v4
        with:
          context: ./openfast
          file: ./openfast/Dockerfile-main
          push: false
          build-args: |
            OPENFAST_MAIN=${{ env.OPENFAST_MAIN }}


      # Dev image
      - name: Build and push Docker - Dev
        if: always()
        uses: docker/build-push-action@v4
        with:
          context: ./openfast
          file: ./openfast/Dockerfile-dev
          push: false
          build-args: |
            OPENFAST_MAIN=${{ env.OPENFAST_DEV }}
