name: Publish a Docker image of OpenFAST main
on:
  push:
    branches: ['main']

env:
  DOCKERREGISTRY: mayankchetan
  GHREGISTRY: ghcr.io/mayankchetan
  IMAGE_NAME: openfast-dev

jobs:
  build-and-push-image:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHREGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKERREGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.GHREGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./openfast
          file: ./base/Dockerfile-main
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}